apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: nodeProject
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: 'search'
        - name: MYSQL_USER
          value: 'user'
        - name: MYSQL_PASSWORD
          value: 'password'
        - name: MYSQL_ROOT_PASSWORD
          value: 'password'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

