version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'search'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    networks:
      - node-networks
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
  app:
    depends_on: 
    - db
    #build: ./
    image: tanmayfuse1221/nodejsapplication
    restart: always
    ports:
      - '8080:8080'
    networks:
      - node-networks
    environment:
      DB_CONNECTIONLIMIT: '10'
      DB_HOST: db
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_NAME: 'search'
volumes:
  my-db:
networks:
  node-networks:
